added macros and lists to battle scripts to make battle scripting much easier
haven1433/HexManiacAdvance pull request #180
Opened 2023-07-21 15:51 UTC by agsmgmaster64

added many of the decomp battle script macros into HMA along with a few new lists to be used for many battle script commands

2023-08-03 04:34 UTC, haven1433 requested changes

2023-08-03 04:34 UTC, haven1433 commented on src/HexManiac.Core/Models/Code/battleScriptReference.txt
> +# general macros
The event script macros all contain `.`, while the basic commands do not. This makes it easy to see at a glance which commands are macros and which are not. I'm considering adding a macro on/off toggle in the future, so it would be good to keep the same convention in battle scripts.

Also, please make all the conditional jumps into `if/goto` or `if/call` statements.

Please add `.` separators in these names, like `chosen.status1.animation` and `if.status3.goto`.

2023-08-03 04:34 UTC, haven1433 commented on src/HexManiac.Core/Models/Code/battleScriptReference.txt
> +# moveend macros
I have a bit of trouble telling what all of these do just based on the name. Consider adding documentation comments to ones that are similar that explain the differences.

2023-08-03 04:34 UTC, haven1433 commented on src/HexManiac.Core/Models/Code/default.toml
> +Name = '''bs_moveeffects'''
Can this be combined with `moveeffectoptions`? Would be nice if this was just one list.

2023-08-03 04:38 UTC, agsmgmaster64 commented on src/HexManiac.Core/Models/Code/default.toml
> +Name = '''bs_moveeffects'''
those cannot be the same list there since they are separate from each other

2023-08-03 04:44 UTC, agsmgmaster64 commented on src/HexManiac.Core/Models/Code/battleScriptReference.txt
> +# general macros
i mainly ported these macros from the decomps and that's why the names are like that, but i'll turn them into macros consistent with the event script macros if it helps

2023-08-03 05:03 UTC, haven1433 commented on src/HexManiac.Core/Models/Code/default.toml
> +Name = '''bs_moveeffects'''
Ok. They looked similar at a glance so I wasn't sure. Seems strange that GF would make two lists so similar without being the same.

2023-08-03 05:05 UTC, haven1433 commented on src/HexManiac.Core/Models/Code/battleScriptReference.txt
> +# general macros
I'm fine with you leaving in the current names as aliases in order to match decomps. Just put them below the `.` versions so that priority goes to the `.` versions during script decompilation.

2023-08-03 05:58 UTC, ShinyTillDawn commented on src/HexManiac.Core/Models/Code/battleScriptReference.txt
> +# moveend macros
I'm guessing that this is whether or not it's a link battle, a replayed battle, a dome tourney battle, or something else.

2023-08-10 02:16 UTC, haven1433 approved these changes

2023-08-10 02:16 UTC, merged