A variety of changes related to HUBOL
haven1433/HexManiacAdvance pull request #222
Opened 2024-05-30 05:50 UTC by ShinyTillDawn

− Fixed a typo.
− Added an updated `moveeffectoptions` [[List]] for newly−created HUBOL ROMs.
− Fixed the number of moves to recognize.

Some things have yet to be tested.

2024-05-30 12:57 UTC, haven1433 commented on src/HexManiac.Core/Models/HardcodeTablesModel.cs
> +	 // Move effects in HUBOL
use spaces instead of tabs in order to make the whitespace consistent

2024-05-30 12:59 UTC, haven1433 commented
@ShinyTillDawn 
Some hubol users have had trouble with editing the type chart. Hubol may be inserting a replacement chart, leaving HMA to point at an unused original chart. Can you investigate?

2024-05-30 15:39 UTC, ShinyTillDawn commented
I tried searching for bytes that would indicate the presence of a new type chart a few months ago, but to no avail. I can try again and fix the spacing.

2024-05-30 17:37 UTC, haven1433 commented
Looks pretty Good! I'll request that you use ".5x" instead of "½x" for effectiveness 5, so that it's easier to type when editing the table. Or if ".5x" causes trouble because of the `.`, maybe "halfx"?

2024-05-31 02:44 UTC, ShinyTillDawn commented
I changed the [[List]] item's name internally and fixed the spacing. It's gonna be hard implementing the type chart support without making a mistake...

2024-06-02 13:34 UTC, haven1433 requested changes
Looking pretty good! Just a few suggestions to make the code a bit easier to read and work with.

2024-06-02 13:34 UTC, haven1433 commented on src/HexManiac.Core/Models/HardcodeTablesModel.cs
>              newList.Add("Me First");
Go ahead and use `newList.AddRange(...)` here like we talked about, to make it easier to read the list and add new elements. Something like...

```cs
newList.AddRange(new [] {
  "Me First",
  "Eat Berry",
  "Natural Gift",
  ...
  "Last Resort or Sky Drop",
  "Damage Set Terrain",
  "Teatime",
});
```

2024-06-02 13:34 UTC, haven1433 commented on src/HexManiac.Core/Models/HardcodeTablesModel.cs
> +            while (newMultipliers.Count <= 5)
Probably the clearest way to do this is to make all the nulls first, and then insert into the indexes that aren't null.
```cs
var newMultipliers = new string[21]; // 0 to 20
newMultipliers[0] = "1x";
newMultipliers[1] = "0x";
newMultipliers[5] = "0.5x";
newMultipliers[20] = "2x";
SetList(new NoDataChangeDeltaModel(), "effectiveness", newMultipliers, null, StoredList.GenerateHash(newMultipliers));
```

2024-06-02 13:34 UTC, haven1433 commented on src/HexManiac.Core/Models/HardcodeTablesModel.cs
> +         // Move effects in HUBOL
I think this commented functionality is handled elsewhere... please remove it before the review is published.

2024-06-02 13:34 UTC, haven1433 commented on src/HexManiac.Core/Models/HardcodeTablesModel.cs
> +            format = "[Norm.effectiveness Fight.effectiveness Fly.effectiveness Poison.effectiveness Grd.effectiveness Rock.effectiveness Bug.effectiveness Ghost.effectiveness Steel.effectiveness par
To make this easier to read, we might construct it up from a list of the types first, and then add the `.` and `effectiveness` annotation. Will also help guard against typos. Maybe something like:
```cs
format = "Norm Fight Fly Poison Grd Rock Bug Ghost Steel t9 Fire Water Grass Elec Psych Ice Drag Dark t18 t19 t20 t21 t22 Fairy";
format = " ".Join(format.Split(' ').Select(type => $"{type}.effectiveness"));
format = $"[{format}]data.pokemon.type.names"
```

2024-06-02 16:27 UTC, ShinyTillDawn commented on src/HexManiac.Core/Models/HardcodeTablesModel.cs
>              newList.Add("Me First");
Previously, this function didn't use `AddRange()` at all. Also, I can't really use `AddRange()` here because I'm _editing_ existing items in the list. Using that list method would require me to rebuild the list from the ground up, which isn't necessary. After `newList[213]`, I could use `AddRange()` as that's the point where new elements are added to the table.

2024-06-02 16:28 UTC, ShinyTillDawn commented on src/HexManiac.Core/Models/HardcodeTablesModel.cs
> +            while (newMultipliers.Count <= 5)
That works even better!

2024-06-02 16:29 UTC, ShinyTillDawn commented on src/HexManiac.Core/Models/HardcodeTablesModel.cs
> +         // Move effects in HUBOL
This was the first attempt at me trying to add the updated move effects, but it's no longer needed after pushing this commit. Thus, I don't think that commented functionality is handled elsewhere.

2024-06-02 16:29 UTC, ShinyTillDawn commented on src/HexManiac.Core/Models/HardcodeTablesModel.cs
> +            format = "[Norm.effectiveness Fight.effectiveness Fly.effectiveness Poison.effectiveness Grd.effectiveness Rock.effectiveness Bug.effectiveness Ghost.effectiveness Steel.effectiveness par
This would definitely be more optimized.

2024-06-04 17:52 UTC, haven1433 commented
It's looking pretty good to me. Mark it as ready for review (not draft) when you're done with the functionality, then I'll do a final pass review before accepting the PR.

2024-06-05 02:44 UTC, haven1433 approved these changes

2024-06-05 02:44 UTC, merged